--Comando básico em linguagem SQL

CREATE DATABASE 

--DDL - LINGUAGEM DE DEFINIÇÃO DE DADOS 
CREATE TABLE ALUNO(
    id INT auto_increment PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE INT NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL
);

ALTER TABLE 

RENAME TABLE ALUNO TO ALUNOS 

DELETE TABLE --Utilizamos para eliminar dados de uma tabela. 

DROP TABLE --Utilizamos para eliminar uma tabela inteira.

--DML - LINGUAGEM DE MODIFICAÇÃO DE DADOS 
INSERT ALUNO(NOME, IDADE, ENDERECO)
VALUES("EDUARDO","20","RUA JAGUATIRICA")

UPDATE ALUNO(NOME, IDADE, ENDERECO)
VALUES("EDUARDO BARBOSA","20","RUA JAGUATIRICA")

--DQL - LINGUAGEM DE CONSULTA DE DADOS 
SELECT * FROM ALUNO 

SELECT NOME FROM ALUNO


